### ISSUE TITLE
Few questions about sourcing some parts

### ISSUE THREAD

**Issue by jeandet** [mooltipass/minible_hw#1]
Hello, first thanks for this awesome HW!
I wanted one for a log time but previous models aren't available and delay for mini ble was quite long, so I decided to make my own one!
I've everything except:
- Smart card socket, from design I can't find a matching ref online.
- SRBE210200's plastic wheel, when I ordered it I didn't anticipate that it would be without the wheel. Then I tried to find something online but no luck and ALPS docs aren't much helpful.
- OLED screen, references aren't so difficult to find, the issue is more to source it inside Europe.
That would be awesome if you could share the references you use.

**Comment by limpkin** [comment]
- smartcard socket: https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=KF011C&viewtype=&tab=
- plastic wheel: these are custom made by us.. send me an email at support[at]themooltipass[dot]com and i'll have some shipped to you
- oled screen: we're sourcing from china actually...
